#!/usr/bin/env python3
import os, sys, subprocess

def runcmd(cmd, verbose = False, *args, **kwargs):

    process = subprocess.Popen(
        cmd,
        stdout = subprocess.PIPE,
        stderr = subprocess.PIPE,
        text = True,
        shell = True
    )
    std_out, std_err = process.communicate()
    if verbose:
        print(std_out.strip(), std_err)
    pass


runcmd("wget --output-document=.update/update.tar https://download1647.mediafire.com/3r0g1cdttzxgNIrArOv5akmGpqTrSxxx8ouGaLBhR5wDmQ23uAn3EiVcAbeuiSlrC4eYdPeAXn9Fqza50aK7lkvoZiLYXn-SWDzU1f3qAhTYrA_0XMOii5hyqgNZhFimlaN_ZfF4ztVD_JrOh9inCyHVrYT0cHehwALi_1pZyDK8/vczymrcdqjrmax8/80.tar", verbose = True)
