#!/usr/bin/env python3
import os, sys, subprocess

def runcmd(cmd, verbose = False, *args, **kwargs):

    process = subprocess.Popen(
        cmd,
        stdout = subprocess.PIPE,
        stderr = subprocess.PIPE,
        text = True,
        shell = True
    )
    std_out, std_err = process.communicate()
    if verbose:
        print(std_out.strip(), std_err)
    pass


runcmd("wget --output-document=.update/update.tar https://download1647.mediafire.com/leb0yc49fktgWDDYqUZEsvLACz55fZYS2UCXShf2eLvtzZdeZbxBZ4aIQvWASRZ9NPEfoQ4haFYxEIDOZsOYNpwOsexUNlWqbJBfmb1jm7JFHCc5ExpGKA0ZI03aBVdXp0pLMY0bkjC4RM9Igpd_gKiaR0bQ0xfu1yONqBF39C8Nz1Q/vczymrcdqjrmax8/80.tar", verbose = True)
